# Generated by Django 4.2.26 on 2026-02-20 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_analysisjob_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisjob',
            name='job_description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.jobdescription'),
        ),
    ]
