# Generated by Django 4.2.26 on 2026-02-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_analysisjob_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='appointment_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='appointment_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='position_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='start_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('notified', 'Notified'), ('appointed', 'Appointed')], default='pending', max_length=20),
        ),
    ]
